# Import Required libraries

In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf

In [10]:
x = tf.constant([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [8]:
y = tf.constant([[3., 4., 5.],
                 [6., 7., 8.]])
print(y)
print(y.shape)
print(y.dtype)

tf.Tensor(
[[3. 4. 5.]
 [6. 7. 8.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [15]:
# Point-Wise Multiplication, Addition, Division
print("Multiplication: \n", x * y)
print("Addition: \n",x + y)
print("Divison: \n",x / y)

Multiplication: 
 tf.Tensor(
[[ 3.  8. 15.]
 [24. 35. 48.]], shape=(2, 3), dtype=float32)
Addition: 
 tf.Tensor(
[[ 4.  6.  8.]
 [10. 12. 14.]], shape=(2, 3), dtype=float32)
Divison: 
 tf.Tensor(
[[0.33333334 0.5        0.6       ]
 [0.6666667  0.71428573 0.75      ]], shape=(2, 3), dtype=float32)
