# Import Required libraries

In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf

In [10]:
x = tf.constant([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [8]:
y = tf.constant([[3., 4., 5.],
                 [6., 7., 8.]])
print(y)
print(y.shape)
print(y.dtype)

tf.Tensor(
[[3. 4. 5.]
 [6. 7. 8.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


#### 1. Element-Wise Multiplication, Addition, Division

In [34]:
print("Multiplication: \n", x * y)
print("*" * 200)
print("Addition: \n",x + y)
print("*" * 200)
print("Divison: \n",x / y)
print("*" * 200)
print("Maximum: \n", tf.maximum(x, y))
print("*" * 200)
print("Minimum: \n", tf.minimum(x, y))
print("*" * 200)
print("Exponential: \n", tf.exp(x))

Multiplication: 
 tf.Tensor(
[[ 3.  8. 15.]
 [24. 35. 48.]], shape=(2, 3), dtype=float32)
********************************************************************************************************************************************************************************************************
Addition: 
 tf.Tensor(
[[ 4.  6.  8.]
 [10. 12. 14.]], shape=(2, 3), dtype=float32)
********************************************************************************************************************************************************************************************************
Divison: 
 tf.Tensor(
[[0.33333334 0.5        0.6       ]
 [0.6666667  0.71428573 0.75      ]], shape=(2, 3), dtype=float32)
********************************************************************************************************************************************************************************************************
Maximum: 
 tf.Tensor(
[[3. 4. 5.]
 [6. 7. 8.]], shape=(2, 3), dtype=float32)
*********************

#### 2. Transpose

In [ ]:
tf.transpose(x) 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

#### 3. Slicing

In [29]:
print("Slicing : \n", tf.concat([x, x], axis = 0)[0:2, 0:2])

Slicing : 
 tf.Tensor(
[[1. 2.]
 [4. 5.]], shape=(2, 2), dtype=float32)


#### 4. Softmax

In [30]:
tf.nn.softmax(x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472846, 0.6652409 ],
       [0.09003057, 0.24472846, 0.6652409 ]], dtype=float32)>

#### 5. Tensorflow math operations

In [35]:
tf.reduce_sum(x, axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6., 15.], dtype=float32)>